# Generated by Django 3.0.3 on 2020-02-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
