# Generated by Django 3.0.3 on 2020-02-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
